language: python
dist: trusty
os: linux
python:
  - "3.6"

install:
  - set -x 
  - pip install .
  - pip install pytest
  - pip freeze
  - which python3.6
  - ls /bin

script:
  - pytest tests

notifications:
  email: false