language: python
dist: trusty
os: linux
python:
  - "3.6"

install:
  - set -x
  - echo $PATH
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - pytest tests

notifications:
  email: false