language: python
dist: trusty
os: linux
python:
  - "3.6"

before_install:
  - deactivate
  - which python3.6

install:
  - set -x
  - deactivate
  - which python3.6
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - pytest tests

notifications:
  email: false