language: generic
os: linux
python:
  - "3.6"
  - "3.8"

before_install:
  - env
  - pyenv versions
  - pyenv local 3.6.7
  - pip --version
  - python3.6 -m venv venv
  - source venv/bin/activate

install:
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - pytest tests

notifications:
  email: false