language: python
dist: trusty
os: linux
python:
  - "3.6"

before_install:
  - VENV_PYTHON_PATH=$(which python | xargs dirname | xargs dirname)
  - echo $VENV_PYTHON_PATH
  - deactivate
  - export ROOT_PYTHON_INTERPRETER=$(which python3.6)
  - echo $ROOT_PYTHON_INTERPRETER
  - source $VENV_PYTHON_PATH/bin/activate

install:
  - pwd
  - python -m venv test_env
  - source ./test_env/bin/activate
  - pip install .
  - pip install pytest
  - pip freeze

script:
  - pytest -s tests

notifications:
  email: false