version: "3"
services:
  master:
    container_name: spark-master
    image: spark-docker
    command: spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /etc/spark-conf
      SPARK_PUBLIC_DNS: localhost
      SPARK_MASTER_WEBUI_PORT: 8080
      PYSPARK_PYTHON: python3.6
      PYSPARK_DRIVER_PYTHON: python3.6
      AWS_ACCESS_KEY_ID: AAA
      AWS_SECRET_ACCESS_KEY: BBBBBBBB
    expose:
      - 7000
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
    ports:
      - 8080:8080
    volumes:
      - ./conf/master:/etc/spark-conf
      - ../..:/cluster-pack

  worker:
    image: spark-docker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_CONF_DIR: /etc/spark-conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
      AWS_ACCESS_KEY_ID: AAA
      AWS_SECRET_ACCESS_KEY: BBBBBBBB
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/etc/spark-conf   

  s3:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: AAA
      MINIO_SECRET_KEY: BBBBBBBB
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./s3_data:/data
